declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_NOW_HOST: string;
    NEXT_PUBLIC_DEV_API_URL: string;
    NEXT_PUBLIC_USER_SIGNUP: string;
    NEXT_PUBLIC_BUSINESS_SIGNUP: string;
    NEXT_PUBLIC_BUSINESS_VERIFICATION: string;
    NEXT_PUBLIC_EMAIL_VERIFICATION: string;
    NEXT_PUBLIC_NICE_MOBILE_VERIFICATION: string;
    NEXT_PUBLIC_USER_EMAIL_VERIFICATION: string;
    NEXT_PUBLIC_BUSINESS_EMAIL_VERIFICATION: string;
  }
}